### ISSUE TITLE
Fresh project testing fails

### ISSUE THREAD

**Issue by matjaz** [ryutamaki/vue-template-webpack-typescript#5]
Following basic default instructions fails
https://github.com/ryutamaki/vue-template-webpack-typescript#usage

```
$ npm run unit

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[5] should be an object.
```

**Comment by ryutamaki** [comment]
Currently, I pushed some commits to be able to run `npm run test` .
However, test is still problem for this project, I'll work on this next.

**Comment by ryutamaki** [comment]
This is still failing I will wait for vue-test-utils v1.0.0 will have been published

**Comment by hyochan** [comment]
I am waiting for this one too. Only e2e is working and unit test is failing for both karma and jest.

**Comment by ghost** [comment]
Unit tests still failing with out of the box configurations. I'm getting this error:

Test suite failed to run

    /Users/christopherlcrum/mWork/learn/vue/typescript/vue-template-webpack-typescript-3/test/unit/specs/HelloWorld.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Vue from "vue";
                                                                                             ^^^^^^
    
    SyntaxError: Unexpected token import
      
      at new Script (vm.js:51:7)
          at Generator.next (<anonymous>)
          at new Promise (<anonymous>)

Are there any quick fixes for this? Thanks.
